### PR TITLE
perf: General optimizations and parameter tuning research

### PR DESCRIPTION
**Pull request by vjohnson1-godaddy**
# Background
Following PR #35, there has been room for optimization. This PR contains the research needed in order to subsequently introduce some of those optimizations

# Change List
- A new notebook
- code used in notebook to compare performance before and after optimization

### CODE REVIEW

**Comment by vjohnson1-godaddy** [comment]
I'm not sure what the best course of action for the SonarCloud check is. It's yelling because I've duplicated parts of the current version into the `notebooks/` directory in order to make a before and after comparison of performance.

Perhaps I should instead include the diff? I can continue to use the CSVs to populate the results of the notebook (will complicate reproducibility, though

**Review by dfu-godaddy — COMMENTED** [review]
Could we have the calculator, metrics, and multiple_testing updated in the same file so we can have a better idea of what is changed in this PR? Besides, can we keep the performance comparison as an internal PDR?

**Comment by vjohnson1-godaddy** [comment]
> Besides, can we keep the performance comparison as an internal PDR?

I think the parameter tuning should be included here, but I can live without including the other stuff. The reason the rest of the optimizations were included was because it would have been impractical to tune those parameters without faster code. I'll just close the PR and we can return to the parameter after it's merged

**Comment by vjohnson1-godaddy** [comment]
I'll just put out a regular PR for the numpy optimizations, and we can circle back to the notebook after that's merged to justify the choice of parameters

**Pull request closed without merging**
