### PR TITLE
feat(multiple_testing_power): support multiple metrics and cohort sample size calculation

### PR DESCRIPTION
**Pull request by xyzou685**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [x] Tests (if applicable)
* [x] Documentation (if applicable)
* [ ] A full explanation here in the PR description of the work done and statistical methods used

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [x] No (breaking changes)

### CODE REVIEW

**Comment by xyzou685** [comment]
This pull request adds the feature to calculate minimum required sample size for multiple decision metrics and/or multiple variants by combining the changes from https://github.com/godaddy/sample-size/pull/26, https://github.com/godaddy/sample-size/pull/30, https://github.com/godaddy/sample-size/pull/33, https://github.com/godaddy/sample-size/pull/32. The statistical method used is elaborated in this [PDR](https://github.secureserver.net/hivemind/pdrs/blob/master/hivemind-power-analysis/Model_the_effect_BH_correction_has_on_Power.md#the-simulation-method), and the test statistics's simulation method is validated in [Validation of test statistics simulation.md](https://github.com/godaddy/sample-size/blob/multiple-testing-calculator/Simulation%20Validation/Validation%20of%20test%20statistics%20simulation.md).

**Review by vjohnson1-godaddy — COMMENTED** [review]
Can you bump the version?

**Comment by pchiang-godaddy** [comment]
@vjohnson1-godaddy we can bump it when we make the release PR: https://github.com/godaddy/sample-size/blob/main/RELEASE.md#1-create-a-release-pr

**Comment by pchiang-godaddy** [comment]
probably good to remember this is a public repo and we should not link internal stuff here. although that PDR seems to be fine without any confidential thing. (just a reminder)

**Review by pchiang-godaddy — APPROVED** [review]

**Comment by xyzou685** [comment]
> Can you bump the version?

As @pchiang-godaddy said, I bumped the version in release PR https://github.com/godaddy/sample-size/pull/37

**Review by vjohnson1-godaddy — APPROVED** [review]

**Comment by xyzou685** [comment]
> probably good to remember this is a public repo and we should not link internal stuff here. although that PDR seems to be fine without any confidential thing. (just a reminder)



> probably good to remember this is a public repo and we should not link internal stuff here. although that PDR seems to be fine without any confidential thing. (just a reminder)

Thanks for reminding. I removed the link just in case, and we can share the content in that PDR later if we get any inquiries about the statistical methods we used.

**Pull request merged**
